---
name: CI

on:
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-2022"]
        type: ["etherscan"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up shell
      if: runner.os == 'Windows'
      run: |
        echo 'C:\msys64\mingw64\bin' >> "$GITHUB_PATH"
        echo 'C:\msys64\usr\bin' >> "$GITHUB_PATH"
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install "solc-select>=v1.0.0b1"
        solc-select use 0.5.7 --always-install
        pip install .
    - name: Run Tests
      env:
        TEST_TYPE: ${{ matrix.type }}
        GITHUB_ETHERSCAN: ${{ secrets.GITHUB_ETHERSCAN }}
      shell: bash
      run: |
        bash "scripts/ci_test_${TEST_TYPE}.sh"
