---
name: Lint Code Base

defaults:
  run:
    # To load bashrc
    shell: bash -ieo pipefail {0}

on:
  pull_request:
    branches: [master, dev]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        type: ["black", "darglint", "mypy", "pylint"]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up nix
        uses: cachix/install-nix-action@v18
      - name: Install just
        run: nix-env -iA nixpkgs.just
      - name: Lint everything
        run: just ${{ matrix.type }}
