---
name: Lint Code Base

on:
  pull_request:
    branches: [master, dev]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        type: ["black", "darglint", "mypy", "pylint"]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up nix
        uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Check nix setup
        run: |
          nix --version
          which nix-env
          realpath $(which nix-shell)
          echo $HOME
          ls -al $HOME
      - name: run linter
        run: nix-shell -p just --run "just ${{ matrix.type }}"
